# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-11 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_type',
            field=models.CharField(choices=[('ogg', 'Ogg'), ('mp3', 'Mp3')], default='mp3', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='music_file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
